# Generated by Django 3.2.8 on 2021-10-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='project_name',
        ),
    ]
