# Generated by Django 3.2.8 on 2022-01-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20220123_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='specialisation',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
