# Generated by Django 3.2.8 on 2022-01-23 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_logo',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
