# Generated by Django 3.2.8 on 2022-01-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_project_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_logo',
            field=models.CharField(blank=True, default='https://picsum.photos/200/300', max_length=255, null=True),
        ),
    ]
