# Generated by Django 3.2.8 on 2022-02-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='age',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_logo',
            field=models.CharField(blank=True, default='https://pic.onlinewebfonts.com/svg/img_98811.png', max_length=255, null=True),
        ),
    ]
