# Generated by Django 3.2.8 on 2022-01-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_project_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='contact_type',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('WA', 'Whatsapp'), ('IG', 'Instagram'), ('LIN', 'Linkedin'), ('GIT', 'Github')], default='WA', max_length=20),
        ),
    ]
