# Generated by Django 3.2.8 on 2022-01-23 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_contactinformation_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='district',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='contact_type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('whatsapp', 'Whatsapp'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('github', 'Github')], default='whatsapp', max_length=20),
        ),
    ]
