# Generated by Django 3.2.8 on 2022-01-23 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20220123_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='certification',
        ),
        migrations.AddField(
            model_name='education',
            name='education_detail',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='education_type',
            field=models.CharField(choices=[('high school', 'High School'), ('intermediate', 'Intermediate'), ('bachelor', 'Bachelor'), ('diploma', 'Diploma'), ('master', 'Master'), ('certification', 'Certification')], default='high school', max_length=20),
        ),
    ]
