# Generated by Django 3.2.8 on 2022-01-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20220123_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_year',
            field=models.DateField(),
        ),
    ]
