# Generated by Django 3.2.8 on 2022-01-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20220123_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_exp_project', to='portfolio.workexperience'),
        ),
    ]
